export const allEmployeeData = [
  {
    id: 1,
    employeeId: "EMP001",
    name: "John Smith",
    email: "john.smith@secureedge.com",
    mobile: "+91 9876543210",
    department: "Engineering",
    designation: "Software Engineer",
    permission: "Admin",
  },
  {
    id: 2,
    employeeId: "EMP002",
    name: "Emily Johnson",
    email: "emily.johnson@secureedge.com",
    mobile: "+91 9876543211",
    department: "Human Resources",
    designation: "HR Manager",
    permission: "Manager",
  },
  {
    id: 3,
    employeeId: "EMP003",
    name: "Michael Brown",
    email: "michael.brown@secureedge.com",
    mobile: "+91 9876543212",
    department: "Finance",
    designation: "Financial Analyst",
    permission: "User",
  },
  {
    id: 4,
    employeeId: "EMP004",
    name: "Sophia Davis",
    email: "sophia.davis@secureedge.com",
    mobile: "+91 9876543213",
    department: "IT",
    designation: "System Administrator",
    permission: "Admin",
  },
  {
    id: 5,
    employeeId: "EMP005",
    name: "Daniel Wilson",
    email: "daniel.wilson@secureedge.com",
    mobile: "+91 9876543214",
    department: "Marketing",
    designation: "Marketing Executive",
    permission: "User",
  },
  {
    id: 6,
    employeeId: "EMP006",
    name: "Olivia Taylor",
    email: "olivia.taylor@secureedge.com",
    mobile: "+91 9876543215",
    department: "Engineering",
    designation: "Frontend Developer",
    permission: "Manager",
  },
  {
    id: 7,
    employeeId: "EMP007",
    name: "James Anderson",
    email: "james.anderson@secureedge.com",
    mobile: "+91 9876543216",
    department: "Engineering",
    designation: "Backend Developer",
    permission: "User",
  },
  {
    id: 8,
    employeeId: "EMP008",
    name: "Emma Thomas",
    email: "emma.thomas@secureedge.com",
    mobile: "+91 9876543217",
    department: "Operations",
    designation: "Operations Executive",
    permission: "Manager",
  },
  {
    id: 9,
    employeeId: "EMP009",
    name: "William Martinez",
    email: "william.martinez@secureedge.com",
    mobile: "+91 9876543218",
    department: "Sales",
    designation: "Sales Manager",
    permission: "Admin",
  },
  {
    id: 10,
    employeeId: "EMP010",
    name: "Ava Garcia",
    email: "ava.garcia@secureedge.com",
    mobile: "+91 9876543219",
    department: "Support",
    designation: "Support Engineer",
    permission: "User",
  },
  {
    id: 11,
    employeeId: "EMP011",
    name: "Benjamin Moore",
    email: "benjamin.moore@secureedge.com",
    mobile: "+91 9876543220",
    department: "Engineering",
    designation: "Full Stack Developer",
    permission: "Admin",
  },
  {
    id: 12,
    employeeId: "EMP012",
    name: "Charlotte White",
    email: "charlotte.white@secureedge.com",
    mobile: "+91 9876543221",
    department: "Legal",
    designation: "Legal Advisor",
    permission: "Manager",
  },
  {
    id: 13,
    employeeId: "EMP013",
    name: "Lucas Harris",
    email: "lucas.harris@secureedge.com",
    mobile: "+91 9876543222",
    department: "Security",
    designation: "Security Analyst",
    permission: "Admin",
  },
  {
    id: 14,
    employeeId: "EMP014",
    name: "Amelia Clark",
    email: "amelia.clark@secureedge.com",
    mobile: "+91 9876543223",
    department: "Quality Assurance",
    designation: "QA Engineer",
    permission: "User",
  },
  {
    id: 15,
    employeeId: "EMP015",
    name: "Henry Lewis",
    email: "henry.lewis@secureedge.com",
    mobile: "+91 9876543224",
    department: "Research",
    designation: "Research Associate",
    permission: "Manager",
  },
  {
    id: 16,
    employeeId: "EMP016",
    name: "Mia Walker",
    email: "mia.walker@secureedge.com",
    mobile: "+91 9876543225",
    department: "Engineering",
    designation: "UI/UX Designer",
    permission: "User",
  },
  {
    id: 17,
    employeeId: "EMP017",
    name: "Alexander Hall",
    email: "alexander.hall@secureedge.com",
    mobile: "+91 9876543226",
    department: "Cloud",
    designation: "Cloud Engineer",
    permission: "Admin",
  },
  {
    id: 18,
    employeeId: "EMP018",
    name: "Harper Allen",
    email: "harper.allen@secureedge.com",
    mobile: "+91 9876543227",
    department: "Business",
    designation: "Business Analyst",
    permission: "Manager",
  },
  {
    id: 19,
    employeeId: "EMP019",
    name: "Ethan Young",
    email: "ethan.young@secureedge.com",
    mobile: "+91 9876543228",
    department: "DevOps",
    designation: "DevOps Engineer",
    permission: "Admin",
  },
  {
    id: 20,
    employeeId: "EMP020",
    name: "Grace King",
    email: "grace.king@secureedge.com",
    mobile: "+91 9876543229",
    department: "Administration",
    designation: "Office Administrator",
    permission: "User",
  },
];