const BlackListEntryData = [
  { srNo: 1, type: "Device", value: "Device-Abc", reason: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", riskType: "High", status: "Active", createdBy: "Admin", createdDate: "12-05-2025", createdTime: "11:30 AM", updatedDate: "12-05-2025", updatedTime: "11:30 AM" },
  { srNo: 2, type: "Device", value: "Device-Abc", reason: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", riskType: "High", status: "Inactive", createdBy: "Admin", createdDate: "12-05-2025", createdTime: "11:30 AM", updatedDate: "12-05-2025", updatedTime: "11:30 AM" },
  { srNo: 3, type: "Device", value: "Device-Abc", reason: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", riskType: "High", status: "Inactive", createdBy: "Admin", createdDate: "12-05-2025", createdTime: "11:30 AM", updatedDate: "12-05-2025", updatedTime: "11:30 AM" },
  { srNo: 4, type: "Device", value: "Device-Abc", reason: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", riskType: "High", status: "Active", createdBy: "Admin", createdDate: "12-05-2025", createdTime: "11:30 AM", updatedDate: "12-05-2025", updatedTime: "11:30 AM" },
  { srNo: 5, type: "Location", value: "Lucknow , India", reason: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", riskType: "High", status: "Active", createdBy: "Admin", createdDate: "12-05-2025", createdTime: "11:30 AM", updatedDate: "12-05-2025", updatedTime: "11:30 AM" },
  { srNo: 6, type: "Location", value: "Lucknow , India", reason: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", riskType: "High", status: "Inactive", createdBy: "Admin", createdDate: "12-05-2025", createdTime: "11:30 AM", updatedDate: "12-05-2025", updatedTime: "11:30 AM" },
  { srNo: 7, type: "IP", value: "IP:34:00:2", reason: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", riskType: "High", status: "Active", createdBy: "Admin", createdDate: "12-05-2025", createdTime: "11:30 AM", updatedDate: "12-05-2025", updatedTime: "11:30 AM" },
  { srNo: 8, type: "IP", value: "IP:34:00:2", reason: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", riskType: "High", status: "Active", createdBy: "Admin", createdDate: "12-05-2025", createdTime: "11:30 AM", updatedDate: "12-05-2025", updatedTime: "11:30 AM" },
  { srNo: 9, type: "IP", value: "IP:34:00:2", reason: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", riskType: "High", status: "Inactive", createdBy: "Admin", createdDate: "12-05-2025", createdTime: "11:30 AM", updatedDate: "12-05-2025", updatedTime: "11:30 AM" },
  { srNo: 10, type: "IP", value: "IP:34:00:2", reason: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", riskType: "High", status: "Active", createdBy: "Admin", createdDate: "12-05-2025", createdTime: "11:30 AM", updatedDate: "12-05-2025", updatedTime: "11:30 AM" },
];

export default BlackListEntryData;
