export const emailFormatData = [
  {
    id: 1,
    bodyText:
      "Lorem Ipsum has been the industry's standard dummy text ever since 1966,",
    subject: "Forgot Email Password",
    templateCode: "Forgot Password",
    channel: "Email",
    createdBy: "Harshit Verma",
    createdDate: "12-05-2025",
    createdTime: "11:30 AM",
    updatedDate: "12-05-2025",
    updatedTime: "11:30 AM",
    status: "True",
  },
  {
    id: 2,
    bodyText:
      "Lorem Ipsum has been the industry's standard dummy text ever since 1966,",
    subject: "Forgot Email Password",
    templateCode: "Forgot Password",
    channel: "Email",
    createdBy: "Harshit Verma",
    createdDate: "12-05-2025",
    createdTime: "11:30 AM",
    updatedDate: "12-05-2025",
    updatedTime: "11:30 AM",
    status: "True",
  },
  {
    id: 3,
    bodyText:
      "Lorem Ipsum has been the industry's standard dummy text ever since 1966,",
    subject: "Forgot Email Password",
    templateCode: "Forgot Password",
    channel: "Email",
    createdBy: "Harshit Verma",
    createdDate: "12-05-2025",
    createdTime: "11:30 AM",
    updatedDate: "12-05-2025",
    updatedTime: "11:30 AM",
    status: "True",
  },
  {
    id: 4,
    bodyText:
      "Lorem Ipsum has been the industry's standard dummy text ever since 1966,",
    subject: "Forgot Email Password",
    templateCode: "Forgot Password",
    channel: "SMS",
    createdBy: "Harshit Verma",
    createdDate: "12-05-2025",
    createdTime: "11:30 AM",
    updatedDate: "12-05-2025",
    updatedTime: "11:30 AM",
    status: "False",
  },
  {
    id: 5,
    bodyText:
      "Lorem Ipsum has been the industry's standard dummy text ever since 1966,",
    subject: "Forgot Email Password",
    templateCode: "Forgot Password",
    channel: "SMS",
    createdBy: "Harshit Verma",
    createdDate: "12-05-2025",
    createdTime: "11:30 AM",
    updatedDate: "12-05-2025",
    updatedTime: "11:30 AM",
    status: "False",
  },
  {
    id: 6,
    bodyText:
      "Lorem Ipsum has been the industry's standard dummy text ever since 1966,",
    subject: "Forgot Email Password",
    templateCode: "Forgot Password",
    channel: "Email",
    createdBy: "Harshit Verma",
    createdDate: "12-05-2025",
    createdTime: "11:30 AM",
    updatedDate: "12-05-2025",
    updatedTime: "11:30 AM",
    status: "True",
  },
  {
    id: 7,
    bodyText:
      "Lorem Ipsum has been the industry's standard dummy text ever since 1966,",
    subject: "Forgot Email Password",
    templateCode: "Forgot Password",
    channel: "SMS",
    createdBy: "Harshit Verma",
    createdDate: "12-05-2025",
    createdTime: "11:30 AM",
    updatedDate: "12-05-2025",
    updatedTime: "11:30 AM",
    status: "True",
  },
  {
    id: 8,
    bodyText:
      "Lorem Ipsum has been the industry's standard dummy text ever since 1966,",
    subject: "Forgot Email Password",
    templateCode: "Forgot Password",
    channel: "Email",
    createdBy: "Harshit Verma",
    createdDate: "12-05-2025",
    createdTime: "11:30 AM",
    updatedDate: "12-05-2025",
    updatedTime: "11:30 AM",
    status: "False",
  },
  {
    id: 9,
    bodyText:
      "Lorem Ipsum has been the industry's standard dummy text ever since 1966,",
    subject: "Forgot Email Password",
    templateCode: "Forgot Password",
    channel: "Email",
    createdBy: "Harshit Verma",
    createdDate: "12-05-2025",
    createdTime: "11:30 AM",
    updatedDate: "12-05-2025",
    updatedTime: "11:30 AM",
    status: "False",
  },
  {
    id: 10,
    bodyText:
      "Lorem Ipsum has been the industry's standard dummy text ever since 1966,",
    subject: "Forgot Email Password",
    templateCode: "Forgot Password",
    channel: "Email",
    createdBy: "Harshit Verma",
    createdDate: "12-05-2025",
    createdTime: "11:30 AM",
    updatedDate: "12-05-2025",
    updatedTime: "11:30 AM",
    status: "False",
  },
];