export const userBlacklistData = [
  {
    id: 1,
    userId: "#23",
    employeeName: "Mohit Singh",
    email: "example@gmail.com",
    mobile: "+91 8976896545",
    status: "Block",
    reason: "Wrong credentials many times",
    riskType: "Low Risk",
    createdBy: "Admin",
    createdAt: "12-05-2025 11:30 AM",
  },
  {
    id: 2,
    userId: "#23",
    employeeName: "Mohit Singh",
    email: "example@gmail.com",
    mobile: "+91 8976896545",
    status: "Block",
    reason: "Wrong credentials many times",
    riskType: "Low Risk",
    createdBy: "Admin",
    createdAt: "12-05-2025 11:30 AM",
  },
  {
    id: 3,
    userId: "#23",
    employeeName: "Mohit Singh",
    email: "example@gmail.com",
    mobile: "+91 8976896545",
    status: "Block",
    reason: "Wrong credentials many times",
    riskType: "High Risk",
    createdBy: "Admin",
    createdAt: "12-05-2025 11:30 AM",
  },
  {
    id: 4,
    userId: "#23",
    employeeName: "Mohit Singh",
    email: "example@gmail.com",
    mobile: "+91 8976896545",
    status: "Block",
    reason: "Wrong credentials many times",
    riskType: "Medium Risk",
    createdBy: "Admin",
    createdAt: "12-05-2025 11:30 AM",
  },
  {
    id: 5,
    userId: "#23",
    employeeName: "Mohit Singh",
    email: "example@gmail.com",
    mobile: "+91 8976896545",
    status: "Block",
    reason: "Wrong credentials many times",
    riskType: "Medium Risk",
    createdBy: "Admin",
    createdAt: "12-05-2025 11:30 AM",
  },
  {
    id: 6,
    userId: "#23",
    employeeName: "Mohit Singh",
    email: "example@gmail.com",
    mobile: "+91 8976896545",
    status: "Block",
    reason: "Wrong credentials many times",
    riskType: "Medium Risk",
    createdBy: "Admin",
    createdAt: "12-05-2025 11:30 AM",
  },
  {
    id: 7,
    userId: "#23",
    employeeName: "Mohit Singh",
    email: "example@gmail.com",
    mobile: "+91 8976896545",
    status: "Block",
    reason: "Wrong credentials many times",
    riskType: "High Risk",
    createdBy: "Admin",
    createdAt: "12-05-2025 11:30 AM",
  },
  {
    id: 8,
    userId: "#23",
    employeeName: "Mohit Singh",
    email: "example@gmail.com",
    mobile: "+91 8976896545",
    status: "Block",
    reason: "Wrong credentials many times",
    riskType: "Medium Risk",
    createdBy: "Admin",
    createdAt: "12-05-2025 11:30 AM",
  },
  {
    id: 9,
    userId: "#23",
    employeeName: "Mohit Singh",
    email: "example@gmail.com",
    mobile: "+91 8976896545",
    status: "Block",
    reason: "Wrong credentials many times",
    riskType: "High Risk",
    createdBy: "Admin",
    createdAt: "12-05-2025 11:30 AM",
  },
  {
    id: 10,
    userId: "#23",
    employeeName: "Mohit Singh",
    email: "example@gmail.com",
    mobile: "+91 8976896545",
    status: "Block",
    reason: "Wrong credentials many times",
    riskType: "Medium Risk",
    createdBy: "Admin",
    createdAt: "12-05-2025 11:30 AM",
  },
  {
    id: 11,
    userId: "#24",
    employeeName: "Rahul Sharma",
    email: "rahul@gmail.com",
    mobile: "+91 9876543210",
    status: "Block",
    reason: "Multiple failed OTP attempts",
    riskType: "High Risk",
    createdBy: "Super Admin",
    createdAt: "14-05-2025 09:45 AM",
  },
  {
    id: 12,
    userId: "#25",
    employeeName: "Priya Verma",
    email: "priya@gmail.com",
    mobile: "+91 9988776655",
    status: "Block",
    reason: "Suspicious login activity",
    riskType: "Low Risk",
    createdBy: "Admin",
    createdAt: "16-05-2025 03:20 PM",
  },
  {
    id: 13,
    userId: "#26",
    employeeName: "Ankit Gupta",
    email: "ankit@gmail.com",
    mobile: "+91 9123456789",
    status: "Block",
    reason: "Fraud transaction detected",
    riskType: "High Risk",
    createdBy: "Security Admin",
    createdAt: "18-05-2025 12:10 PM",
  },
  {
    id: 14,
    userId: "#27",
    employeeName: "Sneha Kapoor",
    email: "sneha@gmail.com",
    mobile: "+91 9090909090",
    status: "Block",
    reason: "Repeated password reset abuse",
    riskType: "Medium Risk",
    createdBy: "Admin",
    createdAt: "19-05-2025 02:40 PM",
  },
  {
    id: 15,
    userId: "#28",
    employeeName: "Amit Kumar",
    email: "amit@gmail.com",
    mobile: "+91 9871234567",
    status: "Block",
    reason: "Account compromise",
    riskType: "High Risk",
    createdBy: "Super Admin",
    createdAt: "20-05-2025 08:50 AM",
  },
  {
    id: 16,
    userId: "#29",
    employeeName: "Neha Singh",
    email: "neha@gmail.com",
    mobile: "+91 9876541230",
    status: "Block",
    reason: "Unauthorized access",
    riskType: "Medium Risk",
    createdBy: "Admin",
    createdAt: "21-05-2025 10:15 AM",
  },
  {
    id: 17,
    userId: "#30",
    employeeName: "Rohit Jain",
    email: "rohit@gmail.com",
    mobile: "+91 9812345678",
    status: "Block",
    reason: "Policy violation",
    riskType: "Low Risk",
    createdBy: "HR Admin",
    createdAt: "22-05-2025 01:05 PM",
  },
  {
    id: 18,
    userId: "#31",
    employeeName: "Karan Mehta",
    email: "karan@gmail.com",
    mobile: "+91 9871122334",
    status: "Block",
    reason: "Too many failed logins",
    riskType: "Medium Risk",
    createdBy: "Admin",
    createdAt: "23-05-2025 11:55 AM",
  },
  {
    id: 19,
    userId: "#32",
    employeeName: "Pooja Arora",
    email: "pooja@gmail.com",
    mobile: "+91 9001122334",
    status: "Block",
    reason: "Suspicious device detected",
    riskType: "High Risk",
    createdBy: "Security Admin",
    createdAt: "24-05-2025 05:35 PM",
  },
  {
    id: 20,
    userId: "#33",
    employeeName: "Vikas Yadav",
    email: "vikas@gmail.com",
    mobile: "+91 9898989898",
    status: "Block",
    reason: "Repeated authentication failure",
    riskType: "Low Risk",
    createdBy: "Admin",
    createdAt: "25-05-2025 09:10 AM",
  },
];